name: Lighthouse CI

on:
  deployment_status:
    types: [success]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    if: |
      github.event.deployment_status.environment == 'Production' &&
      github.event.deployment_status.state == 'success' &&
      !contains(github.event.deployment_status.description, 'preview')
    steps:
      - uses: actions/checkout@v3

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ github.event.deployment_status.target_url }}
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: '.github/lighthouse/config.json'

      - name: Save results
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-results
          path: '.lighthouseci'