name: Lighthouse CI

on:
  deployment_status:
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' || github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@v3

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ github.event.deployment_status.target_url || 'http://localhost:3000' }}
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: ./lighthouserc.js