name: Lighthouse CI

on:
  deployment_status:
    branches: [ main ]
    types: [success]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ github.event.deployment_status.target_url || 'https://love-match-youkeyou110.vercel.app' }}
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: '.github/lighthouse/config.json'

      - name: Save results
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-results
          path: '.lighthouseci'